name: Scheduled Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9,12,18 * * *'
  workflow_dispatch: # allow manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (without tests)
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test --info --stacktrace

      - name: Upload test report
        if: always() # upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: sudo apt-get install -y chromium-chromedriver
